name: self-hosted-demo
on: 
  push:
    branches:
      - main
jobs:
  testing-self-hosted-deployments:
    runs-on: ga-aws
    steps:
      - name: run container
        run: |
          docker container run -d --name webserver1 nginx
